### ISSUE TITLE
UAR incompatible with URP

### ISSUE THREAD

**Issue by marcusx2** [zappar-xr/zappar-unity-examples#7]
I tried to upgrade the Image Tracking 3D Animation example to use the [URP](https://learn.unity.com/tutorial/introduction-to-urp), but this is what happened when I ran the example(yes, it was working with the standard pipeline, this is a specific issue with URP):
https://zapworksforumuploads.s3.dualstack.eu-west-1.amazonaws.com/original/2X/9/9cea72277b35f15a551538bbcf36acfe2d576d17.jpeg,
I would like to ask to make the UAR compatible with URP, at least for WebGL builds. The reason I ask for this is because the URP increases performance dramatically on webgl builds, and it’s essential for slower phones. I know this from experience. On my samsung s8 the example scene runs really slow, but I am sure that if I was able to use URP it would become normal, like it happened before. I was told that it runs super smooth on S10 and on ios 14 it runs super smooth as well from my tests, but clients won’t accept this if it doesn’t run smoothly on lower end devices as well. URP can make slower end devices run webgl builds smoothly, or at least increase performance dramatically, so it can make all the difference. Thank you for your time!

**Comment by nfynt-zap** [comment]
Should be fixed now!

**Comment by marcusx2** [comment]
@nfynt-zap after upgrading the project to URP, I don't see the camera feed anymore

![image](https://user-images.githubusercontent.com/5656275/183777827-5ed5b1fd-0ca2-47c2-b481-f4d3d7be4268.png)


So yea, no errors, but URP is still not supported. It seems like it's the same problem as before, I see the scene from the editor(skybox), and not the camera feed. This is rather disappointing since I reported this on 2020, and now on 2022 it's still not working, and was closed because it "should be fixed"...

**Comment by nfynt-zap** [comment]
Hello @marcusx2 

Can you confirm the following:
- you have updated UAR editor setting to use SRP
- you have updated existing scene (specifically ZapparCamera) for the SRP.

If you're not sure about this. Please read the SRP section on Readme [here](https://github.com/zappar-xr/universal-ar-unity#supporting-unity-scriptable-render-pipeline).

Also there's an examples repo using SRP [here](https://github.com/zappar-xr/unity-example-face-tracking-landmark), so you may wanna check it for reference. 

Feel free to provide a minimum reproducible project for me to test. Though It seems like a setup issue to me.

Best,

**Comment by marcusx2** [comment]
Ah it worked. Thanks, it was my mistake. Performance is a much better with acceptable framerates, even on my old Samsung s8 now. I can finally use this on a real project.
